midl-wrapper: Add -o parameter

diff --git a/bin/midl-wrapper b/bin/midl-wrapper
--- a/bin/midl-wrapper
+++ b/bin/midl-wrapper
@@ -9,6 +9,7 @@
 #  - swallow stdout chatter
 #
 
+
 ##
 ## Configuration
 ##
@@ -16,6 +17,8 @@
 # -Oicf is the preferred option; we cannot use this because the Mingw import
 # library for 'rpcrt4.dll' is missing the function NdrServerCall2. -Oi is
 # deprecated and will eventually be removed.
+#
+# See also: http://msdn.microsoft.com/en-us/library/aa367352(v=VS.85).aspx
 MIDL_STUB_MODE="-Oi"
 
 # Generate C code using GNU cpp to avoid requiring MSVC.
@@ -27,26 +30,45 @@ if [ -z $MIDL ]; then
   MIDL=midl.exe
 fi
 
+
 ##
 ## Script
 ##
 
-if [ -z $1 ]; then
-  echo "Usage: $0 [idl file]"
+if [ "$1" = "-o" ]; then
+  output_path=$2
+  MIDL_OPTIONS="-out $output_path $MIDL_OPTIONS"
+  shift 2
+fi
+
+if [ -z $1 ] || [ $1 == "--help" ]; then
+  echo "\
+Usage: $0 [-o DIR] IDL_FILE
+
+    -o DIR: place generated source files into DIR"
   exit 255
 fi
 
-if [ ! -e $MIDL ]; then
+if [ ! -x $MIDL ]; then
   echo "Unable to locate $MIDL"
-  exit 1
+  exit 2
 fi
 
 idl_file=$1
 
+if [ ! -e $idl_file ]; then
+  echo "Unable to locate $idl_file"
+  exit 1
+fi
+
+$MIDL $MIDL_OPTIONS $idl_file | sed -e /^Processing.*/d
+
 extension=${idl_file##*.}
 base=`basename $idl_file .$extension`
 
-$MIDL $MIDL_OPTIONS $idl_file | sed -e /^Processing.*/d
+if [ -n $output_path ]; then
+  base="$output_path/$base"
+fi
 
 # The generated code for some reason uses 'extern' for forward
 # declarations of constants that are defined further down the same
